version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: "zookeeper"
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    networks:
      - default
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: "kafka"
    container_name: kafka
    depends_on:
      - zookeeper
    env_file:
      - kafka.env
    volumes:
      - kafka-storage:/var/lib/kafka/data
    networks:
      - default
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    hostname: "kafka-ui"
    ports:
      - "8989:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - default
volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-storage:
networks:
  default:
    name: docker_default
    external: true